name: release-tag

on:
  pull_request:
    types: ["opened", "synchronize"]
  push:
    branches:
    - master

jobs:
  release:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: google-github-actions/release-please-action@v3
        id: tag_release
        with:
          command: manifest
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: wangyoucao577/go-release-action@v1
        id: artifact_release
        if: ${{ steps.tag_release.outputs.release_created }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: linux
          goarch: amd64
          project_path: ./internal/
          binary_name: terraform-cloud-provider-releaser
          asset_name: terraform-cloud-provider-releaser-linux-amd64
          release_tag: ${{ steps.tag_release.outputs.tag_name }}